import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/ui/DisableDraftMode";
import { VisualEditing } from "next-sanity";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body>
          {(await draftMode()).isEnabled && (
            <>
              <DisableDraftMode />
              <VisualEditing/>
            </>
          )}
          <main>
            <Header />
            {children}
            <SanityLive />
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
